### ISSUE TITLE
SR: 프로젝트 기획 및 범위 설정

### ISSUE THREAD

**Issue by amazer001** [codestates/BaroYeogiya#1]
### ISSUE
- Group:  `sr`
- Type: `feature`
- Detail: 프로젝트 기획 및 범위 설정

### TODO
1. [x] 아이디어 정리
2. [x] 개발 일정 수립
3. [x] To Do 리스트 작성
4. [x] Wiki 작성
5. [x] Not To Do 리스트 점검
