### ISSUE TITLE
Client : 찜하기 기능 수정 및 마이페이지의 찜 목록,찜 취소 기능 구현

### ISSUE THREAD

**Issue by Brian-free1** [codestates/BaroYeogiya#100]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 찜하기 기능 수정 및 마이페이지의 찜 목록,찜 취소 기능 구현

### TODO
1. [x] 찜하기 기능 수정
2. [x] 마이페이지 찜 목록 기능 구현
3. [x] 마이페이지 찜 취소 기능 구현

### Labels
- Estimated time: `E: 2h`
- Group : `client`
- Sprint: `Sprint__2`
- Urgency: `Middle`
