### ISSUE TITLE
Client : 찜 목록 버튼 기능 수정, 가게 리스트 기능 수정, 매장 등록 기능 수정

### ISSUE THREAD

**Issue by Brian-free1** [codestates/BaroYeogiya#139]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 찜 목록 버튼 기능 수정, 가게 리스트 기능 수정, 매장 등록 기능 수정

### TODO
1. [x] 찜 목록 버튼 기능 수정
2. [x] 가게 리스트 기능 수정
3. [x] 매장 등록 기능 수정( WiP )

### Labels
- Estimated time: `E: 6h`
- Group : `client`
- Sprint: `Sprint__2`
- Urgency: `Low`
