### ISSUE TITLE
Client : 지도 내 장소 검색 중 검색어 자동완성 기능에서 발생하는 오류 수정

### ISSUE THREAD

**Issue by qkrwlgh123** [codestates/BaroYeogiya#146]
### ISSUE
- Group:  client
- Type: bug
- Detail: 자동 검색 기능 중, 중복된 검색어들이 발생하는 오류, 개발자 도구에서 400 Bad request가 발생하는 오류, map을 이용한 여러 엘리먼트 태그 생성 시, key값이 누락되어 발생하는 오류

### TODO
1.  [x] 자동 검색 기능 중, 중복된 검색어들이 발생하는 오류 해결
2.  [x] 개발자 도구에서 확인되는 400 Bad request 오류 해결
3.  [x] key값이 누락되어 발생하는 오류 해결

### Labels
- Estimated time: E: 3h
- Group : client
- Sprint: Sprint__2__
- Urgency: High
