### ISSUE TITLE
Client: 지도 페이지 디자인 및 전체 기능 추가&수정

### ISSUE THREAD

**Issue by amazer001** [codestates/BaroYeogiya#150]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 헤더 디자인

### TODO
1. [x] 지도 재배치
2. [x] 검색창 기능 추가&수정 및 디자인
3. [x] 매장 목록 기능 추가&수정 및 디자인
4. [x] 리뷰 목록 기능 추가&수정 및 디자인
5. [x] 신규 매장 등록창 기능 수정 및 디자인

### Estimated time
Pick one
### Labels
- Estimated time: E: `12h`
- Group : `client`
- Sprint: `Sprint2`
- Urgency: `High`
