### ISSUE TITLE
API: 회원가입 API

### ISSUE THREAD

**Issue by amazer001** [codestates/BaroYeogiya#22]
### ISSUE
- Group:  `server`
- Type: `feature`
- Path: `POST` /user
- Detail: 회원가입 API 제작

### TODO
1. [x] Request parameter 확인
2. [x] 회원정보 중복 확인
3. [x] 회원정보 저장
4. [x] 각 결과별 Response 반환

### Estimated time
Pick one
### Labels
- Estimated time: E: `1.5h`
- Group : `server`
- Sprint: `Sprint2`
- Urgency: `Middle`
