### ISSUE TITLE
API: 회원정보 수정 API

### ISSUE THREAD

**Issue by amazer001** [codestates/BaroYeogiya#25]
### ISSUE
- Group:  `server`
- Type: `feature`
- Path: `PATCH` /user
- Detail: 회원정보 수정 API 제작

### TODO
1. [x] Access token 유효성 검사
2. [x] Request parameter 확인
3. [x] 회원정보 수정
4. [x] 각 결과별 Response 반환

### Estimated time
Pick one
### Labels
- Estimated time: E: `1.5h`
- Group : `server`
- Sprint: `Sprint2`
- Urgency: `Middle`
