### ISSUE TITLE
API: 위치 서비스 API

### ISSUE THREAD

**Issue by amazer001** [codestates/BaroYeogiya#41]
### ISSUE
- Group:  `server`
- Type: `feature`
- Path
   - `GET`, `PUT` /map
   - `GET` /map/pin
- Detail: 위치 관리 서비스 API 제작

### TODO
1. [x] `GET` /map 내 위치 조회 API 제작
2. [x] `PUT` /map 내 위치 저장 API 제작
3. [x] `GET` /map/pin 핀 조회 API 제작

### Estimated time
Pick one
### Labels
- Estimated time: E: `2.5h`
- Group : `server`
- Sprint: `Sprint2`
- Urgency: `Middle`
