### ISSUE TITLE
API: 매장 API

### ISSUE THREAD

**Issue by amazer001** [codestates/BaroYeogiya#43]
### ISSUE
- Group:  `server`
- Type: `feature`
- Path
  - `GET` /store
  - `POST`, `DELETE` /store/:store-uuid
- Detail: 매장 관리 API 제작

### TODO
1. [x] `GET` /store 매장 조회 API 제작
2. [x] `POST` /store 매장 등록 API 제작
4. [x] `PUT` /store 매장 이미지 수정 API 제작
3. [x] `POST` /store/:store-uuid 매장 찜하기 API 제작
5. [x] `DELETE` /store/:store-uuid 매장 찜 취소 API 제작

### Estimated time
Pick one
### Labels
- Estimated time: E: `3h`
- Group : `server`
- Sprint: `Sprint2`
- Urgency: `Middle`
