### ISSUE TITLE
Client : 로그인 모달창 및 회원정보 수정 모달창 보완

### ISSUE THREAD

**Issue by Brian-free1** [codestates/BaroYeogiya#52]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 로그인 모달창 및 회원정보 수정 모달창 보완

### TODO
1. [x] 로그인 모달창 보완
2. [x] 회원정보 수정 모달창 보완
3. [x] Nav bar 기능 구현

### Labels
- Estimated time: `E: 2.5h`
- Group : `client`
- Sprint: `Sprint__2`
- Urgency:  `Middle`
