### ISSUE TITLE
Server: EC2 생성 & 관리

### ISSUE THREAD

**Issue by amazer001** [codestates/BaroYeogiya#7]
### ISSUE
- Group:  `server`
- Type: feature
- Detail: EC2 생성

### TODO
1. [x] EC2 생성
2. [x] node.js & npm 설치
3. [x] 인바운드 규칙 설정
4. [x] RDS 연동 테스트
