### ISSUE TITLE
Server: Sequelize 환경 구축

### ISSUE THREAD

**Issue by amazer001** [codestates/BaroYeogiya#9]
### ISSUE
- Group:  `server`, `database`
- Type: `feature`
- Detail: Sequelize migration 환경 구축

### TODO
1. [x] models 생성 & 설정
2. [x] migrations 생성 & 설정
3. [x] seeders 생성 & 설정
4. [x] RDS 연동 테스트
