### ISSUE TITLE
Client : 리뷰 모달창 세부 기능 구현, 게스트 지도 페이지 구현

### ISSUE THREAD

**Issue by Brian-free1** [codestates/BaroYeogiya#92]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 리뷰 모달창 세부 기능 구현, 게스트 지도 페이지 구현

### TODO
1. [x] 리뷰 삭제 기능 구현
2. [x] 가게 찜하기 기능 구현
3. [x] 리뷰 등록 기능 구현
4. [x] 게스트 지도 페이지 구현

### Labels
- Estimated time: `E: 6h`
- Group : `client`
- Sprint: `Sprint__2`
- Urgency: `Middle`
